[build]
  functions = "functions"  # Specifies the directory where your Netlify functions are located
  command = "npm run build"  # Adjust this based on your project's build command

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
