[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "POST"
      Access-Control-Allow-Headers = "Content-Type"
